version: '3.7'

services:

app:
  image: amigo-secreto-ld
  ports:
    - 3001:3001
  environment:
    MYSQL_HOST: mysql
    MYSQL_USER: root
    MYSQL_PASSWORD: secret
    MYSQL_DB: amigosecretold

mysql:
  image: mysql:5.7
  volumes:
    - ./amigosecretold-mysql-data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: amigosecretold